version: "3.3"
    
services:
  nginx:
    build : ./requirements/nginx/
    restart : always
    depends_on :
      - wordpress
    ports:
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    image : "nginx"
    volumes:
      - wordpress:/var/www/wordpress
  
  mariadb:
    build : ./requirements/mariadb
    restart : always
    ports:
        - "3306:3306"
    privileged : true
    volumes :
      - mariadb:/var/lib/mysql/
    env_file :
      - .env
    networks :
      - mariadb-net
    container_name: "mariadb"
    image : "mariadb"

  wordpress :
    build : ./requirements/wordpress
    env_file : 
      - .env
    restart : always
    ports : 
      - "9000:9000"
    depends_on :
      - mariadb
    volumes :
      - wordpress:/var/www/wordpress
    networks : 
      - php-net
      - mariadb-net
    container_name : "wordpress"
    image : "wordpress"

networks :
  php-net:
  mariadb-net:
  
volumes:
  mariadb:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/matraore/data/mariadb'
  wordpress:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/matraore/data/wordpress'
