version: "3.3"

networks:
    docker-network:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts: 
            o: 'bind'
            type: 'none'
            device: '/home/matraore/data/db'
    websites:
        driver: local
        driver_opts: 
            o: 'bind'
            type: 'none'
            device: '/home/matraore/data/wordpress'

services:
    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        restart: always
        hostname: $DOMAIN_NAME
        domainname: $DOMAIN_NAME
        ports:
            - 443:443
        networks:
            docker-network:
                aliases:
                    - $DOMAIN_NAME
        volumes:
            - websites:/www/
    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        restart: always
        env_file: .env
        environment:
            - WP_DB_NAME=$DATABASE
            - WP_DB_USER=$DB_USER
            - WP_DB_PASS=$DB_PASSWORD
        depends_on:
            - mariadb
        networks:
            - docker-network
        volumes:
            - websites:/var/www/html/
    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: always
        env_file: .env
        networks:
            - docker-network
        volumes:
            - db:/var/lib/mysql
