version: "3.3"
    
services:
  nginx:
    build : ./requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    container_name: "nginx"
    volumes:
      - type: bind
        source: /home/matraore/data/wordpress
        target: /var/www/wordpress