version: '3'
services: 
  db:
    image: mariadb
    command: "userdel mysql; useradd -u 999 mysql; mkdir -p /data/mysql; chown -R mysql:mysql /data/mysql"
    volumes: 
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
  
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    command: "userdel www-data; useradd -u 82 www-data; mkdir -p /data/html; chown -R www-data:www-data /data/html"
    volumes: 
      - /data/html:/var/www/html
    depends_on: 
      - db
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - db
    restart: always
  
  nginx:
    build: ./nginx
    volumes: 
      - /data/html/:/var/www/html
    ports: 
      - 443:443
    links:
      - wordpress